name: Replace Value(s)

description: 'GitHub Action to replace value(s) in a specific file :octocat:'

branding:
  icon: 'edit'
  color: 'green'

inputs:
  file_path:
    description: 'The path to the file to update.'
    required: true
  parameters:
    description: 'The current parameters to replace wit values. Accepts an array.'
    required: true

runs:
  using: composite
  steps:
    - run: echo ${{runner.os}}
      shell: bash
    - run: ${{ github.action_path }}/main.sh
      if: runner.os != 'Windows'
      shell: bash
      env:
        FILE_PATH: ${{ inputs.file_path }}
        PARAMETERS: ${{ inputs.parameters }}
    - run: bash main.sh
      if: runner.os == 'Windows'
      shell: bash
      env:
        FILE_PATH: ${{ inputs.file_path }}
        PARAMETERS: ${{ inputs.parameters }}